### ISSUE TITLE
Twidere crashes when timeline is reloaded

### ISSUE THREAD

**Issue by annando** [TwidereProject/Twidere-Android#1076]
## Expected behavior
No crash.

## Actual behavior
Crash some seconds after the timeline was manually reloaded.

## Steps to reproduce
Reload the timeline.

## Extra info
I'm using it with a Friendica account. I guess it is related to some change we made at Friendica. But since we changed surely 3/4 of the whole code in the meantime (we are currently refactoring the code) we cannot track it down to a single change. So it seems as if we are now doing something that Twidere doesn't like.

Android version: (version code here)
6.0.1.

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: (version code here)
3.7.3 

Build variant:

- [ ] Google
- [X] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [X] GNU Social / StatusNet (Friendica)
- [ ] Mastodon

App settings:

- [X] Custom API
- [X] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Could you provide crash log here or to twidere.project@gmail.com ?

**Comment by annando** [comment]
How do I create the crash log? Is there an option to enable it or is there some place where it is stored?

**Comment by annando** [comment]
@mariotaku can you help me in providing the crash log?

**Comment by mariotaku** [comment]
@annando Yes. See [here](https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat)

**Comment by annando** [comment]
The log says:
```
03-04 09:11:37.123   639   692 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
03-04 09:11:37.123   639   692 E AndroidRuntime: Process: org.mariotaku.twidere, PID: 639
03-04 09:11:37.123   639   692 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-04 09:11:37.123   639   692 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.twidere.util.ContentValuesCreator.createSavedSearch(ContentValuesCreator.kt:62)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.twidere.util.ContentValuesCreator.createSavedSearches(ContentValuesCreator.kt:69)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.twidere.task.twitter.GetSavedSearchesTask.doLongOperation(GetSavedSearchesTask.kt:48)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.twidere.task.twitter.GetSavedSearchesTask.doLongOperation(GetSavedSearchesTask.kt:38)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.abstask.library.AbstractTask.invokeExecute(AbstractTask.java:69)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at org.mariotaku.abstask.library.TaskStarter$AsyncTaskTask.doInBackground(TaskStarter.java:45)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-04 09:11:37.123   639   692 E AndroidRuntime: 	... 4 more
```

**Comment by annando** [comment]
Thanks to the callstack I found it myself. Friendica hadn't returned the ```created_at``` field on the saved searches. The missing field lets Twidere crash.

**Comment by Tedko** [comment]
fixed
