### ISSUE TITLE
Mastodon toot crashes app

### ISSUE THREAD

**Issue by pludi** [TwidereProject/Twidere-Android#1090]
## Expected behavior
Toot displayed

## Actual behavior
App crashes reproducible

## Steps to reproduce
Open https://chaos.social/@pludikovsky/99632245055165457 in Twidere
App crashes

## Extra info
Log output:
```
E/AndroidRuntime(23984): FATAL EXCEPTION: main
E/AndroidRuntime(23984): Process: org.mariotaku.twidere, PID: 23984
E/AndroidRuntime(23984): java.lang.IndexOutOfBoundsException: setSpan (93 ... 146) ends beyond length 145
E/AndroidRuntime(23984): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
E/AndroidRuntime(23984): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:611)
E/AndroidRuntime(23984): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:607)
E/AndroidRuntime(23984): 	at org.mariotaku.twidere.extension.model.SpanItemExtensionsKt.applyTo(SpanItemExtensions.kt:48)
E/AndroidRuntime(23984): 	at org.mariotaku.twidere.view.holder.StatusViewHolder.display(StatusViewHolder.kt:363)
E/AndroidRuntime(23984): 	at org.mariotaku.twidere.adapter.ParcelableStatusesAdapter.onBindViewHolder(ParcelableStatusesAdapter.kt:324)
E/AndroidRuntime(23984): 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
E/AndroidRuntime(23984): 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
E/AndroidRuntime(23984): 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
E/AndroidRuntime(23984): 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
E/AndroidRuntime(23984): 	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
E/AndroidRuntime(23984): 	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
E/AndroidRuntime(23984): 	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
E/AndroidRuntime(23984): 	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
E/AndroidRuntime(23984): 	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
E/AndroidRuntime(23984): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(23984): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23984): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(23984): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(23984): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23984): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(23984): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(23984): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager( 2315):   Force finishing activity 1 org.mariotaku.twidere/.activity.HomeActivity
```

Android version: 5.1.1

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.7.3

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by pludi** [comment]
Closing as probably obsolete as it's >5 years old.
