### ISSUE TITLE
App crashes on sign-in

### ISSUE THREAD

**Issue by atavism** [TwidereProject/Twidere-Android#112]
Running off master
```
04-07 23:25:26.939    1394-1435/? E/AndroidRuntime﹕ FATAL EXCEPTION: pool-3-thread-1
    Process: org.mariotaku.twidere, PID: 1394
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
            at org.mariotaku.twidere.activity.support.SignInActivity$SignInTask.doInBackground(SignInActivity.java:613)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by moshpirit** [comment]
It just has happened to me too using the last version on F-Droid

**Comment by pseudomonas** [comment]
Me too. Uninstall / reinstall did not seem to help.

**Comment by moshpirit** [comment]
I hope the developer fix this soon and release a new version (and if it allows us to use GNU social even better)

**Comment by mariotaku** [comment]
Same problem with #106. merge them into one.
