### ISSUE TITLE
Crash when refreshing Hubzilla feed

### ISSUE THREAD

**Issue by rodneyrod** [TwidereProject/Twidere-Android#1122]
Below is the crash log, sorry about the formatting but it's copied directly off my phone.

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.IllegalStateException: profileImage must not be null
	at org.mariotaku.twidere.extension.model.api.UserExtensionsKt.getProfileImageOfSize(UserExtensions.kt:42)
	at org.mariotaku.twidere.extension.model.api.StatusExtensionsKt.applyTo(StatusExtensions.kt:166)
	at org.mariotaku.twidere.extension.model.api.StatusExtensionsKt.toParcelable(StatusExtensions.kt:60)
	at org.mariotaku.twidere.extension.model.api.StatusExtensionsKt.toParcelable(StatusExtensions.kt:52)
	at org.mariotaku.twidere.extension.model.api.StatusExtensionsKt.toParcelable$default(StatusExtensions.kt:51)
	at org.mariotaku.twidere.task.twitter.GetHomeTimelineTask.getStatuses(GetHomeTimelineTask.kt:79)
	at org.mariotaku.twidere.task.twitter.GetStatusesTask.doLongOperation(GetStatusesTask.kt:88)
	at org.mariotaku.twidere.task.twitter.GetStatusesTask.doLongOperation(GetStatusesTask.kt:46)
	at org.mariotaku.abstask.library.AbstractTask.invokeExecute(AbstractTask.java:69)
	at org.mariotaku.abstask.library.TaskStarter$AsyncTaskTask.doInBackground(TaskStarter.java:45)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by rodneyrod** [comment]
Bit more info on how to reproduce:

1. Create a Twitter account and change server details
2. Change API URL to [HUBZILLA URL]/api
3. Change Auth type to Basic
4. Login to service
5. Try and refresh home feed

Twidere will then crash with the previously quoted error.

**Comment by rodneyrod** [comment]
There may be a compatibility issue with the API too, @redmatrix might be able to help if there is.

**Comment by annando** [comment]
I guess the important part of the error message is "Caused by: java.lang.IllegalStateException: profileImage must not be null". So the API doesn't provide this field.

But you shouldn't use "Twitter", but "Statusnet".

**Comment by rodneyrod** [comment]
@annando It crashes when I set it to Statusnet too, everything else is set the same, so basic auth.

**Comment by redmatrix** [comment]
I can find no field in any version of the twitter/statusnet api called 'profileImage'. There is however a profile_image_url which Hubzilla normally sets. Unfortunately it isn't obvious what specific API endpoint is being accessed here so it may be difficult to troubleshoot without knowing that.

Also be certain the Twitter API addon is enabled on your Hubzilla site. It is optional and is not installed by default.

**Comment by rodneyrod** [comment]
@redmatrix Can confirm that the instance I'm on has it enabled.
