### ISSUE TITLE
Cut chinese text from reply window will crash Twidere

### ISSUE THREAD

**Issue by chenshaoju** [TwidereProject/Twidere-Android#1155]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Cut Chinese text from reply window.

## Actual behavior
Twidere has stopped working

## Steps to reproduce
（My English is poor, Here is Chinese）
１.点击任意推文的回复按钮。
２.输入任意中文。
３.长按输入的中文，并仅选择输入的任意或全部部中文（不含提及部分的ID）。
４.点击“剪切”。
５.Twidere已停止运行。

## Extra info

Android version: (version code here)
8.1

Network type:

- [ ] Cellular
- [X] Wi-Fi

App version: (version code here)
3.7.3

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

Logcat:
```
--------- beginning of crash
10-18 21:18:05.433 22301 22301 E AndroidRuntime: FATAL EXCEPTION: main
10-18 21:18:05.433 22301 22301 E AndroidRuntime: Process: org.mariotaku.twidere, PID: 22301
10-18 21:18:05.433 22301 22301 E AndroidRuntime: java.lang.IndexOutOfBoundsException: charAt: 11 >= length 11
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:123)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.text.SafeSpannableStringBuilder.get(SafeSpannableStringBuilder.kt:11)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.text.SafeSpannableStringBuilder.charAt(SafeSpannableStringBuilder.kt:11)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.CharSequenceCharacterIterator.setIndex(CharSequenceCharacterIterator.java:83)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:929)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.method.WordIterator.isBoundary(WordIterator.java:95)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:5005)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.Editor$HandleView.invalidate(Editor.java:4298)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:5660)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:1863)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView.spanChange(TextView.java:9526)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView$ChangeWatcher.onSpanRemoved(TextView.java:11965)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.sendSpanRemoved(SpannableStringBuilder.java:1281)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:499)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:788)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.ktextension.EditableExtensionsKt.clearSpans(EditableExtensions.kt:29)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.activity.ComposeActivity.updateTextCount(ComposeActivity.kt:1630)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.activity.ComposeActivity.access$updateTextCount(ComposeActivity.kt:119)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.activity.ComposeActivity$setupEditText$2.onTextChanged(ComposeActivity.kt:1781)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView.sendOnTextChanged(TextView.java:9364)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView.handleTextChanged(TextView.java:9451)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:11926)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:227)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView.deleteText_internal(TextView.java:11434)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.TextView.onTextContextMenuItem(TextView.java:10846)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at org.mariotaku.twidere.view.ComposeEditText.onTextContextMenuItem(ComposeEditText.kt:88)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3976)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2459)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:96)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$-com_android_internal_view_FloatingActionMode_4856(FloatingActionMode.java:121)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.$m$0(Unknown Source:4)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.onMenuItemClick(Unknown Source:0)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:425)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.view.View.performClick(View.java:6294)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24770)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-18 21:18:05.433 22301 22301 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-18 21:18:05.436  1301 11349 W ActivityManager:   Force finishing activity org.mariotaku.twidere/.activity.ComposeActivity
10-18 21:18:05.454  1301 11349 W ActivityManager:   Force finishing activity org.mariotaku.twidere/.activity.HomeActivity
```

**Comment by Tedko** [comment]
@chenshaoju #1178 重复了。我先把这个关了。这个也会排上修复日程。
