### ISSUE TITLE
Translate feature crashes the app

### ISSUE THREAD

**Issue by deinodon** [TwidereProject/Twidere-Android#1363]
## Expected behavior
translate tweet
## Actual behavior
crashes

**Comment by chenshaoju** [comment]
Phone: OnePlus 5T
OS: Android 9.0 (OxygenOS 9.0.11)
Twidere Version:4.1.4 (Google Play)

logcat:

[code]09-09 22:19:36.390 15086 15086 W riotaku.twider: Accessing hidden method Landroid/content/res/Resources$Theme;->rebase()V (dark greylist, reflection)
09-09 22:19:36.394 15086 15086 I ResourcesCompat: Failed to retrieve rebase() method
09-09 22:19:36.394 15086 15086 I ResourcesCompat: java.lang.NoSuchMethodException: rebase []
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at java.lang.Class.getMethod(Class.java:2068)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at java.lang.Class.getDeclaredMethod(Class.java:2047)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at androidx.core.content.res.ResourcesCompat$ThemeCompat$ImplApi23.rebase(ResourcesCompat.java:501)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at androidx.core.content.res.ResourcesCompat$ThemeCompat.rebase(ResourcesCompat.java:477)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext2(AppCompatDelegateImpl.java:465)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:110)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at org.mariotaku.twidere.activity.BaseActivity.attachBaseContext(BaseActivity.kt:367)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.Activity.attach(Activity.java:7064)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3007)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.os.Handler.dispatchMessage(Handler.java:106)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.os.Looper.loop(Looper.java:193)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at android.app.ActivityThread.main(ActivityThread.java:6898)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at java.lang.reflect.Method.invoke(Native Method)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
09-09 22:19:36.394 15086 15086 I ResourcesCompat:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-09 22:19:36.411 15086 15086 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
09-09 22:19:36.412 15086 15086 D AppCompatDelegate: updateForNightMode [allowRecreation:false, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:false, canReturnDifferentContext:true, host:org.mariotaku.twidere.activity.HomeActivity@4708e0d]
09-09 22:19:36.412 15086 15086 D AppCompatDelegate: updateForNightMode not recreating Activity: org.mariotaku.twidere.activity.HomeActivity@4708e0d
09-09 22:19:36.412 15086 15086 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: -1 for host:org.mariotaku.twidere.activity.HomeActivity@4708e0d
09-09 22:19:36.571 15086 15086 D AppCompatDelegate: updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:org.mariotaku.twidere.activity.HomeActivity@4708e0d]
09-09 22:19:36.571 15086 15086 D AppCompatDelegate: updateForNightMode not recreating Activity: org.mariotaku.twidere.activity.HomeActivity@4708e0d
09-09 22:19:36.571 15086 15086 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: -1 for host:org.mariotaku.twidere.activity.HomeActivity@4708e0d
09-09 22:19:36.581 15086 15086 I TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.[/code]

**Comment by ykm** [comment]
+1...on samsung m30s, android 10

**Comment by Aidenat9** [comment]
how to resolve this crash

**Comment by ykm** [comment]
@Aidenat9 https://github.com/TwidereProject/Twidere-Android/issues/624
