### ISSUE TITLE
4.1.5 constantly crashes

### ISSUE THREAD

**Issue by oprudkyi** [TwidereProject/Twidere-Android#1401]
After update to 4.1.5 twidere doesn't start and crashes. 
also when trying to install 4.1.4 it don't install 

![image](https://user-images.githubusercontent.com/3018472/100696665-bb95bf00-339c-11eb-8616-fd357824d3f4.png)
![image](https://user-images.githubusercontent.com/3018472/100696685-ca7c7180-339c-11eb-880a-aa660d276d06.png)

Android version: 8.0

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.1.5

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by herbsmn** [comment]
4.1.5 crashed on my Galaxy Note II device running the https://replicant.us OS today. I was able to downgrade back to 4.1.4 by uninstalling the app and then re-installing 4.1.4.

**Comment by hkramski** [comment]
Both the F-Droid and the Google releases are affected by these crashes (Android 8.1.0 here).

**Comment by gldhnchn** [comment]
can confirm with f droid build on Android 7.1.2

**Comment by roytam1** [comment]
confirmed with Xperia XZ1 Compact (Android 8.0)

**Comment by ilf** [comment]
Same. Logcat:

```
12-02 17:30:46.422 25080 25080 D AppCompatDelegate: Application config ({1.0 262mcc3mnc [en_US] ldltr sw411dp w411dp h707dp 560dpi nrml long port finger -keyb/v/h -nav/h s.10}) matches base context config, using empty base overlay
12-02 17:30:46.422 25080 25080 D AppCompatDelegate: Applying night mode using ContextThemeWrapper and applyOverrideConfiguration(). Config: {0.0 ?mcc?mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?touch ?keyb/?/? ?nav/?}
12-02 17:30:46.503 25080 25080 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-02 17:30:46.505 25080 25080 D AppCompatDelegate: updateForNightMode [allowRecreation:false, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:false, canReturnDifferentContext:true, host:org.mariotaku.twidere.activity.MainActivity@70699af]
12-02 17:30:46.506 25080 25080 D AppCompatDelegate: updateForNightMode not recreating Activity: org.mariotaku.twidere.activity.MainActivity@70699af
12-02 17:30:46.506 25080 25080 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: -1 for host:org.mariotaku.twidere.activity.MainActivity@70699af
12-02 17:30:46.512 25080 25080 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-02 17:30:46.620 25080 25080 D AppCompatDelegate: updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:org.mariotaku.twidere.activity.MainActivity@70699af]
12-02 17:30:46.620 25080 25080 D AppCompatDelegate: updateForNightMode not recreating Activity: org.mariotaku.twidere.activity.MainActivity@70699af
12-02 17:30:46.620 25080 25080 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: -1 for host:org.mariotaku.twidere.activity.MainActivity@70699af
12-02 17:30:46.629 25080 25080 I TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.
12-02 17:30:46.706 25080 25080 D AppCompatDelegate: Application config ({1.0 262mcc3mnc [en_US] ldltr sw411dp w411dp h707dp 560dpi nrml long port finger -keyb/v/h -nav/h s.10}) matches base context config, using empty base overlay
12-02 17:30:46.706 25080 25080 D AppCompatDelegate: Applying night mode using ContextThemeWrapper and applyOverrideConfiguration(). Config: {0.0 ?mcc?mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?touch ?keyb/?/? ?nav/?}
12-02 17:30:46.717 25080 25080 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-02 17:30:46.721 25080 25080 D AppCompatDelegate: updateForNightMode [allowRecreation:false, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:false, canReturnDifferentContext:true, host:org.mariotaku.twidere.activity.HomeActivity@35fcbb2]
12-02 17:30:46.721 25080 25080 D AppCompatDelegate: updateForNightMode not recreating Activity: org.mariotaku.twidere.activity.HomeActivity@35fcbb2
12-02 17:30:46.722 25080 25080 D AppCompatDelegate: updateForNightMode. Skipping. Night mode: -1 for host:org.mariotaku.twidere.activity.HomeActivity@35fcbb2
12-02 17:30:46.740 25080 25080 D AndroidRuntime: Shutting down VM
12-02 17:30:46.741 25080 25080 E AndroidRuntime: FATAL EXCEPTION: main
12-02 17:30:46.741 25080 25080 E AndroidRuntime: Process: org.mariotaku.twidere, PID: 25080
12-02 17:30:46.741 25080 25080 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;I)V in class Landroid/app/ActivityManager$TaskDescription; or its super classes (declaration of 'android.app.ActivityManager$TaskDescription' appears in /system/framework/framework.jar)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at org.mariotaku.twidere.util.support.ActivitySupport$ActivitySupportL.toNativeTaskDescription(ActivitySupport.java:48)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at org.mariotaku.twidere.util.support.ActivitySupport$ActivitySupportL.setTaskDescription(ActivitySupport.java:44)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at org.mariotaku.twidere.util.support.ActivitySupport.setTaskDescription(ActivitySupport.java:28)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at org.mariotaku.twidere.activity.BaseActivity.onCreate(BaseActivity.kt:268)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at org.mariotaku.twidere.activity.HomeActivity.onCreate(HomeActivity.kt:194)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-02 17:30:46.741 25080 25080 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-02 17:30:48.866 21742 22146 I ActivityManager: Killing 25080:org.mariotaku.twidere/u0a81 (adj 900): crash
12-02 17:30:48.867 21742 22146 D ActivityManager: cleanUpApplicationRecord -- 25080
```

**Comment by yoshimo** [comment]
https://github.com/TwidereProject/Twidere-Android/commits/maintenance looks like that problem is already solved

**Comment by berberic2** [comment]
Can confirm for Fairphone 2 and Lenovo Tab4.

**Comment by Tedko** [comment]
https://github.com/TwidereProject/Twidere-Android/commit/dc144f068e12c4edeccd971c6cf95b6b8f961152 fixed by 4.1.6 

F-droid will pull release from git so sorry folks we cannot make it faster... sorry to cause this trouble.

**Comment by dscottboggs** [comment]
Confirmed, 4.1.6 from the GH releases page works. Thanks guys :grinning:

**Comment by Tedko** [comment]
Thanks for supporting!

**Comment by peter099** [comment]
I can confirm that too. I can't start the app after updating. I am using android 7.1.2.

**Comment by oprudkyi** [comment]
4.1.6 works. thank you @Tlaster @mariotaku 
I am closing issue now.
