### ISSUE TITLE
App crashes when opened (Twidere 4.1.5 via F-Droid on Android 7.1.2)

### ISSUE THREAD

**Issue by elchenberg** [TwidereProject/Twidere-Android#1404]
## Crash Report

```
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=4.1.5
BRAND=motorola
PHONE_MODEL=Moto G
CUSTOM_DATA=preferences.theme=dark
	preferences.theme_bg_option=default
	build.hardware=qcom
	build.product=lineage_falcon
	build.model=Moto G
	build.manufacturer=motorola
	preferences.theme_bg_alpha=160
	build.device=falcon_umts
	last_activity=android.intent.action.MAIN: null (MainActivity)
	build.display=lineage_falcon-userdebug 7.1.2 NJH47F f4535aec29
	debug=false
	twidere.accounts=[redacted], [redacted]
	build.brand=motorola
STACK_TRACE=java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;I)V in class Landroid/app/ActivityManager$TaskDescription; or its super classes (declaration of 'android.app.ActivityManager$TaskDescription' appears in /system/framework/framework.jar)
	at org.mariotaku.twidere.util.support.ActivitySupport$ActivitySupportL.toNativeTaskDescription(ActivitySupport.java:48)
	at org.mariotaku.twidere.util.support.ActivitySupport$ActivitySupportL.setTaskDescription(ActivitySupport.java:44)
	at org.mariotaku.twidere.util.support.ActivitySupport.setTaskDescription(ActivitySupport.java:28)
	at org.mariotaku.twidere.activity.BaseActivity.onCreate(BaseActivity.kt:268)
	at org.mariotaku.twidere.activity.HomeActivity.onCreate(HomeActivity.kt:194)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by elchenberg** [comment]
duplicate of #1403
