### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by xbloq** [TwidereProject/Twidere-Android#639]
Hi

S5 with CM14 nightly & twidere3.2.9

I suppose it's a problem with CM14, some differents apps has similar problem.

2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/databases: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/WebViewChromiumPrefs.xml
2016-11-12 12:55:29,WARNING,cr_AwBrowserProcess,Unknown,Failed to create lock file /data/user/0/org.mariotaku.twidere/app_webview/webview_data.lock
java.io.FileNotFoundException: /data/user/0/org.mariotaku.twidere/app_webview/webview_data.lock: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:455)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
	at org.chromium.android_webview.AwBrowserProcess.tryObtainingDataDirLockOrDie(AwBrowserProcess.java:107)
	at org.chromium.android_webview.AwBrowserProcess.start(AwBrowserProcess.java:74)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:312)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.ensureChromiumStartedLocked(WebViewChromiumFactoryProvider.java:253)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(WebViewChromiumFactoryProvider.java:395)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1246)
	at org.mariotaku.twidere.util.UserAgentUtils$NewApiWrapper.getDefaultUserAgent(UserAgentUtils.java:125)
	at org.mariotaku.twidere.util.UserAgentUtils.getDefaultUserAgentString(UserAgentUtils.java:49)
	at org.mariotaku.twidere.util.UserAgentUtils.getDefaultUserAgentStringSafe(UserAgentUtils.java:79)
	at org.mariotaku.twidere.util.media.TwidereMediaDownloader.<init>(TwidereMediaDownloader.java:61)
	at org.mariotaku.twidere.util.dagger.ApplicationModule.mediaDownloader(ApplicationModule.kt:205)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_MediaDownloaderFactory.get(ApplicationModule_MediaDownloaderFactory.java:37)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_MediaDownloaderFactory.get(ApplicationModule_MediaDownloaderFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_ImageLoaderFactory.get(ApplicationModule_ImageLoaderFactory.java:37)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_ImageLoaderFactory.get(ApplicationModule_ImageLoaderFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.mariotaku.twidere.provider.TwidereDataProvider_MembersInjector.injectMembers(TwidereDataProvider_MembersInjector.java:115)
	at org.mariotaku.twidere.provider.TwidereDataProvider_MembersInjector.injectMembers(TwidereDataProvider_MembersInjector.java:18)
	at org.mariotaku.twidere.util.dagger.DaggerGeneralComponent.inject(DaggerGeneralComponent.java:692)
	at org.mariotaku.twidere.provider.TwidereDataProvider.onCreate(TwidereDataProvider.java:592)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5822)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5414)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5353)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
	at libcore.io.IoBridge.open(IoBridge.java:441)
	... 35 more

2016-11-12 12:55:29,WARNING,riotaku.twidere,Unknown,type=1400 audit(0.0:87414): avc: denied { read } for name="gpuclk" dev="sysfs" ino=19610 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_heme-engine_light]].xml
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_heme-engine_dark]].xml
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_theme-engine]].xml
2016-11-12 12:55:29,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/databases: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:29,ERROR,SQLiteLog,Unknown,(14) os_unix.c:32456: (2) open(/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite) - 

2016-11-12 12:55:29,ERROR,SQLiteDatabase,Unknown,Failed to open database '/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.mariotaku.twidere.provider.TwidereDataProvider.onCreateSQLiteDatabase(TwidereDataProvider.java:609)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.tryCreateDatabase(SQLiteDatabaseWrapper.java:112)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.query(SQLiteDatabaseWrapper.java:70)
	at org.mariotaku.twidere.provider.TwidereDataProvider.query(TwidereDataProvider.java:791)
	at android.content.ContentProvider.query(ContentProvider.java:1020)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at org.mariotaku.twidere.util.DataStoreUtils.getAccountKeys(DataStoreUtils.java:767)
	at org.mariotaku.twidere.util.Utils.hasAutoRefreshAccounts(Utils.java:906)
	at org.mariotaku.twidere.util.Utils$1.run(Utils.java:1226)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

2016-11-12 12:55:29,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/org.mariotaku.twidere_preferences.xml
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/databases: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SQLiteLog,Unknown,(14) os_unix.c:32456: (2) open(/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite) - 

2016-11-12 12:55:30,ERROR,SQLiteDatabase,Unknown,Failed to open database '/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.mariotaku.twidere.provider.TwidereDataProvider.onCreateSQLiteDatabase(TwidereDataProvider.java:609)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.tryCreateDatabase(SQLiteDatabaseWrapper.java:112)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.query(SQLiteDatabaseWrapper.java:70)
	at org.mariotaku.twidere.provider.TwidereDataProvider.query(TwidereDataProvider.java:791)
	at android.content.ContentProvider.query(ContentProvider.java:1020)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at org.mariotaku.twidere.util.DataStoreUtils.hasAccount(DataStoreUtils.java:786)
	at org.mariotaku.twidere.activity.HomeActivity.onCreate(HomeActivity.kt:306)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2602)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/databases: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/WebViewChromiumPrefs.xml
2016-11-12 12:55:30,WARNING,cr_AwBrowserProcess,Unknown,Failed to create lock file /data/user/0/org.mariotaku.twidere/app_webview/webview_data.lock
java.io.FileNotFoundException: /data/user/0/org.mariotaku.twidere/app_webview/webview_data.lock: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:455)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
	at org.chromium.android_webview.AwBrowserProcess.tryObtainingDataDirLockOrDie(AwBrowserProcess.java:107)
	at org.chromium.android_webview.AwBrowserProcess.start(AwBrowserProcess.java:74)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:312)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.ensureChromiumStartedLocked(WebViewChromiumFactoryProvider.java:253)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(WebViewChromiumFactoryProvider.java:395)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1246)
	at org.mariotaku.twidere.util.UserAgentUtils$NewApiWrapper.getDefaultUserAgent(UserAgentUtils.java:125)
	at org.mariotaku.twidere.util.UserAgentUtils.getDefaultUserAgentString(UserAgentUtils.java:49)
	at org.mariotaku.twidere.util.UserAgentUtils.getDefaultUserAgentStringSafe(UserAgentUtils.java:79)
	at org.mariotaku.twidere.util.media.TwidereMediaDownloader.<init>(TwidereMediaDownloader.java:61)
	at org.mariotaku.twidere.util.dagger.ApplicationModule.mediaDownloader(ApplicationModule.kt:205)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_MediaDownloaderFactory.get(ApplicationModule_MediaDownloaderFactory.java:37)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_MediaDownloaderFactory.get(ApplicationModule_MediaDownloaderFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_ImageLoaderFactory.get(ApplicationModule_ImageLoaderFactory.java:37)
	at org.mariotaku.twidere.util.dagger.ApplicationModule_ImageLoaderFactory.get(ApplicationModule_ImageLoaderFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.mariotaku.twidere.provider.TwidereDataProvider_MembersInjector.injectMembers(TwidereDataProvider_MembersInjector.java:115)
	at org.mariotaku.twidere.provider.TwidereDataProvider_MembersInjector.injectMembers(TwidereDataProvider_MembersInjector.java:18)
	at org.mariotaku.twidere.util.dagger.DaggerGeneralComponent.inject(DaggerGeneralComponent.java:692)
	at org.mariotaku.twidere.provider.TwidereDataProvider.onCreate(TwidereDataProvider.java:592)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5822)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5414)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5353)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
	at libcore.io.IoBridge.open(IoBridge.java:441)
	... 35 more

2016-11-12 12:55:30,WARNING,riotaku.twidere,Unknown,type=1400 audit(0.0:87415): avc: denied { read } for name="gpuclk" dev="sysfs" ino=19610 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/cache: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_heme-engine_light]].xml
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_heme-engine_dark]].xml
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/shared_prefs: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SharedPreferencesImpl,Unknown,Couldn't create directory for SharedPreferences file /data/user/0/org.mariotaku.twidere/shared_prefs/[[afollestad_theme-engine]].xml
2016-11-12 12:55:30,WARNING,ContextImpl,Unknown,Failed to ensure /data/user/0/org.mariotaku.twidere/databases: mkdir failed: ENOENT (No such file or directory)
2016-11-12 12:55:30,ERROR,SQLiteLog,Unknown,(14) os_unix.c:32456: (2) open(/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite) - 

2016-11-12 12:55:30,ERROR,SQLiteDatabase,Unknown,Failed to open database '/data/user/0/org.mariotaku.twidere/databases/twidere.sqlite'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.mariotaku.twidere.provider.TwidereDataProvider.onCreateSQLiteDatabase(TwidereDataProvider.java:609)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.tryCreateDatabase(SQLiteDatabaseWrapper.java:112)
	at org.mariotaku.twidere.util.SQLiteDatabaseWrapper.query(SQLiteDatabaseWrapper.java:70)
	at org.mariotaku.twidere.provider.TwidereDataProvider.query(TwidereDataProvider.java:791)
	at android.content.ContentProvider.query(ContentProvider.java:1020)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at org.mariotaku.twidere.util.DataStoreUtils.getAccountKeys(DataStoreUtils.java:767)
	at org.mariotaku.twidere.util.Utils.hasAutoRefreshAccounts(Utils.java:906)
	at org.mariotaku.twidere.util.Utils$1.run(Utils.java:1226)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

2016-11-12 12:55:30,ERROR,ActivityManager,Sistema Android,Found activity ActivityRecord{41f4cfb u0 org.mariotaku.twidere/.activity.HomeActivity t327 f} in proc activity list using null instead of expected ProcessRecord{ea41b25 21083:org.mariotaku.twidere/u0a117}

**Comment by mariotaku** [comment]
I guess it's more like system problem, so closing unless problem resurfaced on stable CM builds.
