### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by Rbagman** [TwidereProject/Twidere-Android#669]
Twidere 3.3.29
Android 4.4.2
Samsung GT-7100

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.LinkHandlerActivity}: android.view.InflateException: Binary XML file line #51: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
	at android.app.ActivityThread.access$1000(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #51: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at org.mariotaku.twidere.fragment.UserFragment.onCreateView(UserFragment.kt:632)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2832)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
	at com.afollestad.appthemeengine.ATEActivity.onStart(ATEActivity.java:29)
	at org.mariotaku.twidere.activity.LinkHandlerActivity.onStart(LinkHandlerActivity.kt:192)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
	at android.app.Activity.performStart(Activity.java:5461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:600)
	... 36 more
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:541)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:571)
	at org.mariotaku.sprite.library.AnimatedBitmapLayer.<init>(AnimatedBitmapLayer.java:51)
	at org.mariotaku.twidere.view.BirthdayView.init(BirthdayView.java:56)
	at org.mariotaku.twidere.view.BirthdayView.<init>(BirthdayView.java:46)
	... 39 more

**Comment by orithena** [comment]
I see an OutOfMemoryError in there. Please reboot your device and try again (sometimes, the system memory has a memory leak, especially if you used the camera a lot -- you can check your reserved system memory in Androids Settings -> Apps -> Active; it should be below 500MB). If the problem persists, please report back.
