### ISSUE TITLE
[Bug] New Twidere button causes force crash

### ISSUE THREAD

**Issue by soaringowl2145** [TwidereProject/Twidere-Android#676]
The button labeled twidere with infinity symbol in the left menu causes force crash.

Also what is this button supposed to do?

**Comment by mariotaku** [comment]
It's some enhanced (paid) features currently in beta, is it downloaded from Google Play Store?

**Comment by soaringowl2145** [comment]
No.  This is the free version from F-Droid version something .35.  Also F-Droid currently recommends this version as stable.  Will the feature be removed from F-Droid version since they only allow free and not paid software?

Thanks.

**Comment by Jiack214** [comment]
I have the same problem.
(I've the  F-Droid version 3.3.35 too. I'm on a device whitout Google Play Services.)

**Comment by mariotaku** [comment]
This entry will be removed from F-Droid first until I find some truly open source payment method.

Free [doesn't means](https://opensource.com/resources/what-open-source) free of charge, but don't worry, I'll keep F-Droid variant 100% open sourced without any single line of propertiary library.

BTW 3.3.35 is a pre-release, does f-droid have some way to use code from `master` branch only?

**Comment by soaringowl2145** [comment]
Thanks.  

I am not sure about that though.  You would need to check their documentation and/or contact them.

**Comment by Rbagman** [comment]
Samsung GT-N7100/Android 4.4.2
Upgraded to same version on F-Droid.


java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi/toast_frame.9.png from drawable resource ID #0x1080096: .xml extension required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi/toast_frame.9.png from drawable resource ID #0x1080096: .xml extension required
	at android.content.res.Resources.loadColorStateList(Resources.java:3611)
	at android.content.res.TypedArray.getColor(TypedArray.java:320)
	at android.content.res.XResources$XTypedArray.getColor(XResources.java:889)
	at org.mariotaku.chameleon.Chameleon$Theme.from(Chameleon.java:446)
	at org.mariotaku.twidere.activity.BaseActivity$userTheme$2.invoke(BaseActivity.kt:102)
	at org.mariotaku.twidere.activity.BaseActivity$userTheme$2.invoke(BaseActivity.kt:71)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.mariotaku.twidere.activity.BaseActivity.getUserTheme(BaseActivity.kt)
	at org.mariotaku.twidere.activity.BaseActivity.getOverrideTheme(BaseActivity.kt:379)
	at org.mariotaku.chameleon.Chameleon.getOverrideTheme(Chameleon.java:132)
	at org.mariotaku.chameleon.Chameleon.<init>(Chameleon.java:53)
	at org.mariotaku.chameleon.Chameleon.getInstance(Chameleon.java:62)
	at org.mariotaku.chameleon.ChameleonActivity.onCreate(ChameleonActivity.java:23)
	at org.mariotaku.twidere.activity.BaseActivity.onCreate(BaseActivity.kt:186)
	at org.mariotaku.twidere.activity.MainActivity.onCreate(MainActivity.kt:34)
	at android.app.Activity.performCreate(Activity.java:5451)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
	... 12 more
