### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by Rbagman** [TwidereProject/Twidere-Android#708]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at com.nostra13.universalimageloader.utils.IoUtils.copyStream(IoUtils.java:74)
	at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.save(LruDiskCache.java:155)
	at org.mariotaku.twidere.loader.MicroBlogAPIStatusesLoader.saveCachedData(MicroBlogAPIStatusesLoader.kt:236)
	at org.mariotaku.twidere.loader.MicroBlogAPIStatusesLoader.loadInBackground(MicroBlogAPIStatusesLoader.kt:182)
	at org.mariotaku.twidere.loader.MicroBlogAPIStatusesLoader.loadInBackground(MicroBlogAPIStatusesLoader.kt:55)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more

Android version: (4.4.2)

Network type:

- [ ] Cellular
- [ x] Wi-Fi

App version: (3.4.9)

Build variant:

- [ ] Google
- [ x] F-Droid

Micro-blogging service:

- [x ] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
OOME could happen everywhere due to insufficient runtime memory. Closing this issue.
