### ISSUE TITLE
Crashes when clicking on a link

### ISSUE THREAD

**Issue by joesse** [TwidereProject/Twidere-Android#729]
Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Expected behavior
Should open the link in browser
## Actual behavior
"unfortunately Twidere was ended"
## Steps to reproduce
In twitter everything works fine
find a queet with an Internet link in the Gnusocial timeline 
Open the link
Same result whether you open it directly in the timeline or in the queet display
## Extra info

Android version: (version code here)
5.1.1
Network type:

- [ ] Cellular
- [ X] Wi-Fi

App version: (version code here)
3.4.39
Build variant:

- [ ] Google
- [ X] F-Droid

Micro-blogging service:

- [ ] Twitter
- [ ] Fanfou
- [ X] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ X] Media preview enabled

**Comment by mariotaku** [comment]
Can you grab logcat tagged with 'AndroidRuntime'?

Usage: `adb logcat -s AndroidRuntime`

**Comment by rugk** [comment]
```
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.MediaViewerActivity: +183ms (total +2m58s100ms)
V/TwidereDns(16676): Resolved [pbs.twimg.com/192.229.233.50]
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.MediaViewerActivity: +192ms
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.LinkHandlerActivity: +310ms
V/TwidereDns(16676): Resolved [pbs.twimg.com/192.229.233.50]
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.MediaViewerActivity: +188ms
V/TwidereDns(16676): Resolved [www.gscon.org/88.99.105.98]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [mobile.twitter.com/199.16.156.43]
V/TwidereDns(16676): Resolved [mobile.twitter.com/199.16.156.43]
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.LinkHandlerActivity: +489ms
V/TwidereDns(16676): Resolved [pbs.twimg.com/93.184.220.70]
V/TwidereDns(16676): Resolved [pbs.twimg.com/93.184.220.70]
V/TwidereDns(16676): Resolved [pbs.twimg.com/93.184.220.70]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(16676): Resolved [mobile.twitter.com/199.16.156.43]
V/TwidereDns(16676): Resolved [mobile.twitter.com/199.16.156.43]
E/AndroidRuntime(16676): Process: org.mariotaku.twidere, PID: 16676
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity.instantiateMediaFragment(MediaViewerActivity.kt:330)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity.onFitSystemWindows(MediaViewerActivity.kt:385)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity$onCreate$1.onApplyWindowInsets(MediaViewerActivity.kt:144)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.view.TintedStatusFrameLayout$1.onApplyWindowInsets(TintedStatusFrameLayout.java:89)
W/XPrivacy(29565): Hooking package=org.mariotaku.twidere
I/art     (29565): Rejecting re-init on previously-failed class java.lang.Class<org.mariotaku.twidere.service.StreamingService$updateStreamingInstances$1>
I/art     (29565): Rejecting re-init on previously-failed class java.lang.Class<org.mariotaku.twidere.service.StreamingService$updateStreamingInstances$1>
I/ActivityManager( 2903): Displayed org.mariotaku.twidere/.activity.HomeActivity: +1s169ms (total +3s18ms)
V/TwidereDns(29565): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(29565): Resolved [twitter.com/104.244.42.65, twitter.com/104.244.42.193]
V/TwidereDns(29565): Resolved [gnusocial.de/37.120.188.233]
V/TwidereDns(29565): Resolved [mobile.twitter.com/199.16.156.43, mobile.twitter.com/199.16.156.107]
V/TwidereDns(29565): Resolved [mobile.twitter.com/199.16.156.43, mobile.twitter.com/199.16.156.107]
V/TwidereDns(29565): Resolved [api.twitter.com/104.244.42.130, api.twitter.com/104.244.42.2, api.twitter.com/104.244.42.66, api.twitter.com/104.244.42.194]
E/AndroidRuntime(29565): Process: org.mariotaku.twidere, PID: 29565
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity.instantiateMediaFragment(MediaViewerActivity.kt:330)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity.onFitSystemWindows(MediaViewerActivity.kt:385)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity$onCreate$1.onApplyWindowInsets(MediaViewerActivity.kt:144)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.view.TintedStatusFrameLayout$1.onApplyWindowInsets(TintedStatusFrameLayout.java:89)
W/XPrivacy(30053): Hooking package=org.mariotaku.twidere
```

**Comment by mariotaku** [comment]
@rugk Thanks, but this log is incomplete. Grab by `logcat -s AndroidRuntime` to get **crashes** rather than `logcat | grep -i twidere`. If you believe your log contains private information, you remove parts not start with `Process: org.mariotaku.twidere, PID: ?????`

**Comment by rugk** [comment]
```
AndroidRuntime(16676): FATAL EXCEPTION: main
E/AndroidRuntime(16676): Process: org.mariotaku.twidere, PID: 16676
E/AndroidRuntime(16676): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime(16676): java.lang.UnsupportedOperationException: ParcelableMedia{url='https://gnusocial.de/notice/9447273', media_url='https://twitter.com/realDonaldTrump/status/843088518339612673', preview_url='null', type=0, width=0, height=0, video_info=null, card=null, page_url='https://gnusocial.de/notice/9447273'}
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity.instantiateMediaFragment(MediaViewerActivity.kt:330)
E/AndroidRuntime(16676): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:100)
E/AndroidRuntime(16676): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:84)
E/AndroidRuntime(16676): 	at android.support.v4.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:109)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity.onFitSystemWindows(MediaViewerActivity.kt:385)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.activity.MediaViewerActivity$onCreate$1.onApplyWindowInsets(MediaViewerActivity.kt:144)
E/AndroidRuntime(16676): 	at org.mariotaku.twidere.view.TintedStatusFrameLayout$1.onApplyWindowInsets(TintedStatusFrameLayout.java:89)
E/AndroidRuntime(16676): 	at android.support.v4.view.ViewCompat$LollipopViewCompatImpl$1.onApplyWindowInsets(ViewCompat.java:1666)
E/AndroidRuntime(16676): 	at android.support.v4.view.ViewCompatLollipop$1.onApplyWindowInsets(ViewCompatLollipop.java:76)
E/AndroidRuntime(16676): 	at android.view.View.dispatchApplyWindowInsets(View.java:7254)
E/AndroidRuntime(16676): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6270)
E/AndroidRuntime(16676): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6274)
E/AndroidRuntime(16676): 	at android.view.View.fitSystemWindows(View.java:7142)
E/AndroidRuntime(16676): 	at android.support.v7.widget.ContentFrameLayout.dispatchFitSystemWindows(ContentFrameLayout.java:72)
E/AndroidRuntime(16676): 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:390)
E/AndroidRuntime(16676): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(16676): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(16676): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(16676): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(16676): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(16676): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
E/AndroidRuntime(16676): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
E/AndroidRuntime(16676): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
E/AndroidRuntime(16676): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(16676): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(16676): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(16676): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
E/AndroidRuntime(16676): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(16676): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
E/AndroidRuntime(16676): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
E/AndroidRuntime(16676): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
E/AndroidRuntime(16676): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
E/AndroidRuntime(16676): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
E/AndroidRuntime(16676): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/AndroidRuntime(16676): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/AndroidRuntime(16676): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
E/AndroidRuntime(16676): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/AndroidRuntime(16676): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(16676): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16676): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(16676): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/AndroidRuntime(16676): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16676): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(16676): 	at com
E/AndroidRuntime(29565): FATAL EXCEPTION: main
E/AndroidRuntime(29565): Process: org.mariotaku.twidere, PID: 29565
E/AndroidRuntime(29565): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime(29565): java.lang.UnsupportedOperationException: ParcelableMedia{url='https://gnusocial.de/notice/9447273', media_url='https://twitter.com/realDonaldTrump/status/843088518339612673', preview_url='null', type=0, width=0, height=0, video_info=null, card=null, page_url='https://gnusocial.de/notice/9447273'}
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity.instantiateMediaFragment(MediaViewerActivity.kt:330)
E/AndroidRuntime(29565): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:100)
E/AndroidRuntime(29565): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:84)
E/AndroidRuntime(29565): 	at android.support.v4.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:109)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity.onFitSystemWindows(MediaViewerActivity.kt:385)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.activity.MediaViewerActivity$onCreate$1.onApplyWindowInsets(MediaViewerActivity.kt:144)
E/AndroidRuntime(29565): 	at org.mariotaku.twidere.view.TintedStatusFrameLayout$1.onApplyWindowInsets(TintedStatusFrameLayout.java:89)
E/AndroidRuntime(29565): 	at android.support.v4.view.ViewCompat$LollipopViewCompatImpl$1.onApplyWindowInsets(ViewCompat.java:1666)
E/AndroidRuntime(29565): 	at android.support.v4.view.ViewCompatLollipop$1.onApplyWindowInsets(ViewCompatLollipop.java:76)
E/AndroidRuntime(29565): 	at android.view.View.dispatchApplyWindowInsets(View.java:7254)
E/AndroidRuntime(29565): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6270)
E/AndroidRuntime(29565): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6274)
E/AndroidRuntime(29565): 	at android.view.View.fitSystemWindows(View.java:7142)
E/AndroidRuntime(29565): 	at android.support.v7.widget.ContentFrameLayout.dispatchFitSystemWindows(ContentFrameLayout.java:72)
E/AndroidRuntime(29565): 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:390)
E/AndroidRuntime(29565): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(29565): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(29565): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(29565): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(29565): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(29565): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
E/AndroidRuntime(29565): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
E/AndroidRuntime(29565): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
E/AndroidRuntime(29565): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(29565): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(29565): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(29565): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
E/AndroidRuntime(29565): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(29565): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
E/AndroidRuntime(29565): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
E/AndroidRuntime(29565): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
E/AndroidRuntime(29565): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
E/AndroidRuntime(29565): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
E/AndroidRuntime(29565): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/AndroidRuntime(29565): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/AndroidRuntime(29565): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
E/AndroidRuntime(29565): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/AndroidRuntime(29565): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(29565): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(29565): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(29565): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/AndroidRuntime(29565): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29565): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(29565): 	at com
```

**Comment by rugk** [comment]
Also crashes when a I tap on a pic from GNUSocial:

```
E/AndroidRuntime(32015): FATAL EXCEPTION: main
E/AndroidRuntime(32015): Process: org.mariotaku.twidere, PID: 32015
E/AndroidRuntime(32015): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime(32015): java.lang.UnsupportedOperationException: ParcelableMedia{url='https://gnusocial.de/notice/9447113', media_url='https://wolke.g5r.eu/s/PqyWtAvRwjj84kW', preview_url='https://gnusocial.de/attachments/thumb/oembed-40b4d5e2616f81fa381ace56c8a489329c27697f0d07c92e27f7f0b8bde83474.jpg', type=0, width=0, height=0, video_info=null, card=null, page_url='https://gnusocial.de/notice/9447113'}
E/AndroidRuntime(32015): 	at org.mariotaku.twidere.activity.MediaViewerActivity.instantiateMediaFragment(MediaViewerActivity.kt:330)
E/AndroidRuntime(32015): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:100)
E/AndroidRuntime(32015): 	at org.mariotaku.mediaviewer.library.IMediaViewerActivity$MediaPagerAdapter.getItem(IMediaViewerActivity.java:84)
E/AndroidRuntime(32015): 	at android.support.v4.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:109)
E/AndroidRuntime(32015): 	at org.mariotaku.twidere.activity.MediaViewerActivity.onFitSystemWindows(MediaViewerActivity.kt:385)
E/AndroidRuntime(32015): 	at org.mariotaku.twidere.activity.MediaViewerActivity$onCreate$1.onApplyWindowInsets(MediaViewerActivity.kt:144)
E/AndroidRuntime(32015): 	at org.mariotaku.twidere.view.TintedStatusFrameLayout$1.onApplyWindowInsets(TintedStatusFrameLayout.java:89)
E/AndroidRuntime(32015): 	at android.support.v4.view.ViewCompat$LollipopViewCompatImpl$1.onApplyWindowInsets(ViewCompat.java:1666)
E/AndroidRuntime(32015): 	at android.support.v4.view.ViewCompatLollipop$1.onApplyWindowInsets(ViewCompatLollipop.java:76)
E/AndroidRuntime(32015): 	at android.view.View.dispatchApplyWindowInsets(View.java:7254)
E/AndroidRuntime(32015): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6270)
E/AndroidRuntime(32015): 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:6274)
E/AndroidRuntime(32015): 	at android.view.View.fitSystemWindows(View.java:7142)
E/AndroidRuntime(32015): 	at android.support.v7.widget.ContentFrameLayout.dispatchFitSystemWindows(ContentFrameLayout.java:72)
E/AndroidRuntime(32015): 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:390)
E/AndroidRuntime(32015): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(32015): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(32015): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(32015): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(32015): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(32015): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
E/AndroidRuntime(32015): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
E/AndroidRuntime(32015): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
E/AndroidRuntime(32015): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(32015): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/AndroidRuntime(32015): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(32015): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
E/AndroidRuntime(32015): 	at android.view.View.measure(View.java:18799)
E/AndroidRuntime(32015): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
E/AndroidRuntime(32015): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
E/AndroidRuntime(32015): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
E/AndroidRuntime(32015): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
E/AndroidRuntime(32015): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
E/AndroidRuntime(32015): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/AndroidRuntime(32015): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/AndroidRuntime(32015): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
E/AndroidRuntime(32015): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/AndroidRuntime(32015): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(32015): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32015): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(32015): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/AndroidRuntime(32015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32015): 	at 
```
