### ISSUE TITLE
Crash when clicking on some tabs

### ISSUE THREAD

**Issue by mamins1376** [TwidereProject/Twidere-Android#732]
Installed Version: 3.4.39 from F-Droid
Android Version: 5.1.1

To Reproduce:
Start the app, tap on one of the home or notifications tab, and then tap on it again.

this bug introduced after updating to latest available on F-Droid.

**Comment by mariotaku** [comment]
Can you grab logcat about this crash? `adb logcat -s AndroidRuntime` will print out log required.

**Comment by mamins1376** [comment]
this is the head of traceback. I thought it was just repeated multiple times and so that I've removed some of the result. tell me if you need that part too.

```
--------- beginning of crash
E/AndroidRuntime(26415): FATAL EXCEPTION: main
E/AndroidRuntime(26415): Process: org.mariotaku.twidere, PID: 26415
E/AndroidRuntime(26415): java.lang.IndexOutOfBoundsException: index: 0, valid range is 0..-1
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.adapter.ParcelableStatusesAdapter.getStatus(ParcelableStatusesAdapter.kt:441)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.adapter.ParcelableStatusesAdapter.getStatus(ParcelableStatusesAdapter.kt:160)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.adapter.iface.IStatusesAdapter$DefaultImpls.getStatus$default(IStatusesAdapter.kt:47)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.fragment.AbsStatusesFragment.saveReadPosition(AbsStatusesFragment.kt:489)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.fragment.AbsStatusesFragment.scrollToStart(AbsStatusesFragment.kt:468)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.adapter.SupportTabsAdapter.onPageReselected(SupportTabsAdapter.kt:136)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.view.TabPagerIndicator.dispatchTabClick(TabPagerIndicator.java:186)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.view.TabPagerIndicator.access$000(TabPagerIndicator.java:44)
E/AndroidRuntime(26415): 	at org.mariotaku.twidere.view.TabPagerIndicator$TabItemHolder.onClick(TabPagerIndicator.java:519)
E/AndroidRuntime(26415): 	at android.view.View.performClick(View.java:4789)
E/AndroidRuntime(26415): 	at android.view.View$PerformClick.run(View.java:19881)
E/AndroidRuntime(26415): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(26415): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26415): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(26415): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(26415): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26415): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26415): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(26415): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by mariotaku** [comment]
@mamins1376 This did help. I fixed this in earlier commits, and it will be available soon.

**Comment by iknownothingaboutcomputers** [comment]
@mariotaku Twidere also crashes after swiping to refresh 'Media'.

**Comment by mariotaku** [comment]
@iknownothingaboutcomputers Not sure if it's related, could you provide a logcat?
