### ISSUE TITLE
Crash on clicking retweet titles – IllegalStateException: statusId must not be null

### ISSUE THREAD

**Issue by bentolor** [TwidereProject/Twidere-Android#874]
## Expected behavior
On clicking a title of a retweeted tweet I expect to open the normal view as regular

## Actual behavior
Twidere just crashes / closes. Restarting reveals the same UI. Error is stable reproduceable. Deleteing Media Cache / Database did not mend.

## Steps to reproduce
This only happens for

- retweets
- on clicking the retweet title (User Name @username) or the tweet itself.

Clicking on the profile icons works as long pressing the tweet does.

## Extra info

````
ANDROID_VERSION=7.1.1
APP_VERSION_NAME=3.6.19
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A3003
CUSTOM_DATA=preferences.theme=dark
	preferences.theme_bg_option=default
	build.hardware=qcom
	build.product=OnePlus3
	build.model=ONEPLUS A3003
	build.manufacturer=OnePlus
	preferences.theme_bg_alpha=160
	build.device=OnePlus3T
	last_activity=android.intent.action.VIEW: twidere://status?account_key=XXXXXXXXXX%40twitter.com&status_id=875395365482233856 (LinkHandlerActivity)
	build.display=ONEPLUS A3003_28_170610
	debug=false
	twidere.accounts=XXXXXXXXXx
	build.brand=OnePlus
STACK_TRACE=java.lang.IllegalStateException: statusId must not be null
	at org.mariotaku.twidere.fragment.StatusFragment$statusActivityLoaderCallback$1.onCreateLoader(StatusFragment.kt:203)
	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
	at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:603)
	at org.mariotaku.twidere.fragment.StatusFragment.loadActivity(StatusFragment.kt:507)
	at org.mariotaku.twidere.fragment.StatusFragment.onLoadFinished(StatusFragment.kt:406)
	at org.mariotaku.twidere.fragment.StatusFragment.onLoadFinished(StatusFragment.kt:134)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
````

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: (version code here)
3.6.19

Build variant:

- [x] F-Droid

Micro-blogging service:

- [x] Twitter

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by bentolor** [comment]
Maybe a dup of #867. Did not find this issue in the first run ...

**Comment by bentolor** [comment]
After reading the other issues: This one for sure this is a duplicate of the #867.

Updated version yet not available on fdroid.
