### ISSUE TITLE
Twidere crashes when trying to open a tweet

### ISSUE THREAD

**Issue by kranich** [TwidereProject/Twidere-Android#879]
## Expected behavior

App crashes.

## Actual behavior

Display tweet.

## Steps to reproduce

Open Twidere. Click on any tweet on home screen. App crashes.

## Extra info

I run Twidere on LineageOS without Gapps.

`adb logcat` yields what follows

```
06-19 17:38:06.174  3562  3657 I ActivityManager: Displayed org.mariotaku.twidere/.activity.HomeActivity: +561ms (total +3m7s672ms)
06-19 17:38:08.997  3562  6287 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=twidere://status?account_key=2979995103@twitter.com&status_id=876822030917742592 cmp=org.mariotaku.twidere/.activity.LinkHandlerActivity (has extras)} from uid 10087 on display 0
06-19 17:38:09.036 13034 13034 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
06-19 17:38:09.116 13034 13034 I TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.
06-19 17:38:09.186 13034 13034 D AndroidRuntime: Shutting down VM
06-19 17:38:09.187 13034 13034 E AndroidRuntime: FATAL EXCEPTION: main
06-19 17:38:09.187 13034 13034 E AndroidRuntime: Process: org.mariotaku.twidere, PID: 13034
06-19 17:38:09.187 13034 13034 E AndroidRuntime: java.lang.IllegalStateException: statusId must not be null
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at org.mariotaku.twidere.fragment.StatusFragment$statusActivityLoaderCallback$1.onCreateLoader(StatusFragment.kt:203)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:603)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at org.mariotaku.twidere.fragment.StatusFragment.loadActivity(StatusFragment.kt:507)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at org.mariotaku.twidere.fragment.StatusFragment.onLoadFinished(StatusFragment.kt:406)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at org.mariotaku.twidere.fragment.StatusFragment.onLoadFinished(StatusFragment.kt:134)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-19 17:38:09.187 13034 13034 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-19 17:38:09.190  3562 29215 W ActivityManager:   Force finishing activity org.mariotaku.twidere/.activity.LinkHandlerActivity
06-19 17:38:09.197  3562 29215 W ActivityManager:   Force finishing activity org.mariotaku.twidere/.activity.HomeActivity
06-19 17:38:09.205 13034 13034 I Process : Sending signal. PID: 13034 SIG: 9
06-19 17:38:09.246  3562 17762 I WindowManager: WIN DEATH: Window{510b631 u0 org.mariotaku.twidere/org.mariotaku.twidere.activity.LinkHandlerActivity}
06-19 17:38:09.247  3562  6287 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=54, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@a86b116)
06-19 17:38:09.247  3562 21540 I ActivityManager: Process org.mariotaku.twidere (pid 13034) has died
06-19 17:38:09.247  3562 21540 D ActivityManager: cleanUpApplicationRecord -- 13034
06-19 17:38:09.249  3562  5320 D GraphicsStats: Buffer count: 12
06-19 17:38:09.250  3562  4283 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=54, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
06-19 17:38:09.254  3562  4043 W InputDispatcher: channel '47d43bc org.mariotaku.twidere/org.mariotaku.twidere.activity.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-19 17:38:09.255  3562  4043 E InputDispatcher: channel '47d43bc org.mariotaku.twidere/org.mariotaku.twidere.activity.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-19 17:38:09.256  3562  4623 I WindowManager: WIN DEATH: Window{47d43bc u0 org.mariotaku.twidere/org.mariotaku.twidere.activity.HomeActivity}
```

Android version: 7.1.2

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 3.6.19

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [x] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment]
This is a duplicate to #867. F-Droid somehow stopped update and I'm not able to trigger its build.
