### ISSUE TITLE
"No value for duration_millis" toast and errors on logcat

### ISSUE THREAD

**Issue by mkody** [TwidereProject/Twidere-Android#90]
I got a toast notification saying "No value for duration_millis". It's a *Warn* on the logcat. Also, I got some *Error*s after it.

```
03-26 21:07:31.483  16097-19160/org.mariotaku.twidere W/Twidere﹕ No value for duration_millis
            at twitter4j.internal.json.MediaEntityJSONImpl.<init>(MediaEntityJSONImpl.java:110)
            at twitter4j.internal.json.StatusJSONImpl.init(StatusJSONImpl.java:464)
            at twitter4j.internal.json.StatusJSONImpl.<init>(StatusJSONImpl.java:111)
            at twitter4j.internal.json.StatusJSONImpl.createStatusList(StatusJSONImpl.java:498)
            at twitter4j.internal.json.InternalJSONFactoryImpl.createStatusList(InternalJSONFactoryImpl.java:237)
            at twitter4j.TwitterImpl.getHomeTimeline(TwitterImpl.java:670)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetHomeTimelineTask.getStatuses(AsyncTwitterWrapper.java:1862)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2123)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2025)
            at org.mariotaku.twidere.task.TwidereAsyncTask$BackgroundRunnable.run(TwidereAsyncTask.java:138)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: org.json.JSONException: No value for duration_millis
            at org.json.JSONObject.get(JSONObject.java:389)
            at org.json.JSONObject.getLong(JSONObject.java:514)
            at twitter4j.internal.json.MediaEntityJSONImpl$VideoInfoJSONImpl.<init>(MediaEntityJSONImpl.java:297)
            at twitter4j.internal.json.MediaEntityJSONImpl.<init>(MediaEntityJSONImpl.java:97)
            at twitter4j.internal.json.StatusJSONImpl.init(StatusJSONImpl.java:464)
            at twitter4j.internal.json.StatusJSONImpl.<init>(StatusJSONImpl.java:111)
            at twitter4j.internal.json.StatusJSONImpl.createStatusList(StatusJSONImpl.java:498)
            at twitter4j.internal.json.InternalJSONFactoryImpl.createStatusList(InternalJSONFactoryImpl.java:237)
            at twitter4j.TwitterImpl.getHomeTimeline(TwitterImpl.java:670)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetHomeTimelineTask.getStatuses(AsyncTwitterWrapper.java:1862)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2123)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2025)
            at org.mariotaku.twidere.task.TwidereAsyncTask$BackgroundRunnable.run(TwidereAsyncTask.java:138)
            at java.lang.Thread.run(Thread.java:818)
03-26 21:07:31.550  16097-19154/org.mariotaku.twidere W/Twidere﹕ No value for duration_millis
            at twitter4j.internal.json.MediaEntityJSONImpl.<init>(MediaEntityJSONImpl.java:110)
            at twitter4j.internal.json.StatusJSONImpl.init(StatusJSONImpl.java:464)
            at twitter4j.internal.json.StatusJSONImpl.<init>(StatusJSONImpl.java:111)
            at twitter4j.internal.json.StatusJSONImpl.createStatusList(StatusJSONImpl.java:498)
            at twitter4j.internal.json.InternalJSONFactoryImpl.createStatusList(InternalJSONFactoryImpl.java:237)
            at twitter4j.TwitterImpl.getHomeTimeline(TwitterImpl.java:670)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetHomeTimelineTask.getStatuses(AsyncTwitterWrapper.java:1862)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2123)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2025)
            at org.mariotaku.twidere.task.TwidereAsyncTask$BackgroundRunnable.run(TwidereAsyncTask.java:138)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: org.json.JSONException: No value for duration_millis
            at org.json.JSONObject.get(JSONObject.java:389)
            at org.json.JSONObject.getLong(JSONObject.java:514)
            at twitter4j.internal.json.MediaEntityJSONImpl$VideoInfoJSONImpl.<init>(MediaEntityJSONImpl.java:297)
            at twitter4j.internal.json.MediaEntityJSONImpl.<init>(MediaEntityJSONImpl.java:97)
            at twitter4j.internal.json.StatusJSONImpl.init(StatusJSONImpl.java:464)
            at twitter4j.internal.json.StatusJSONImpl.<init>(StatusJSONImpl.java:111)
            at twitter4j.internal.json.StatusJSONImpl.createStatusList(StatusJSONImpl.java:498)
            at twitter4j.internal.json.InternalJSONFactoryImpl.createStatusList(InternalJSONFactoryImpl.java:237)
            at twitter4j.TwitterImpl.getHomeTimeline(TwitterImpl.java:670)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetHomeTimelineTask.getStatuses(AsyncTwitterWrapper.java:1862)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2123)
            at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetStatusesTask.doInBackground(AsyncTwitterWrapper.java:2025)
            at org.mariotaku.twidere.task.TwidereAsyncTask$BackgroundRunnable.run(TwidereAsyncTask.java:138)
            at java.lang.Thread.run(Thread.java:818)
03-26 21:09:09.656  16097-16112/org.mariotaku.twidere W/art﹕ Suspending all threads took: 276.762ms
03-26 21:09:10.104  16097-16426/org.mariotaku.twidere E/BitmapFactory﹕ Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.mariotaku.twidere/cache/full_image_cache/1wj1m6lpd557fcrac3fvntkk0: open failed: ENOENT (No such file or directory)
03-26 21:11:34.376  16097-16097/org.mariotaku.twidere W/View﹕ requestLayout() improperly called by android.widget.ListView{1a7e77a7 VFED.VC. ......ID 0,0-864,1776 #7f0d0131 app:id/left_drawer} during layout: running second layout pass
03-26 21:11:34.379  16097-16097/org.mariotaku.twidere W/View﹕ requestLayout() improperly called by android.widget.ListView{3c5ebf49 VFED.VC. ......ID 0,0-864,1557 #102000a android:id/list} during layout: running second layout pass
03-26 21:17:04.950  16097-16097/org.mariotaku.twidere E/StrictMode﹕ class org.mariotaku.twidere.activity.support.LinkHandlerActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class org.mariotaku.twidere.activity.support.LinkHandlerActivity; instances=2; limit=1
            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
```

**Comment by mariotaku** [comment]
seems it's a streaming video. I'll ignore this field now, make it at least able to get tweets.

**Comment by mariotaku** [comment]
fixed.
