### ISSUE TITLE
"IllegalStateException: Fragment" on user tweets view

### ISSUE THREAD

**Issue by fanf** [TwidereProject/Twidere-Android#916]
On twidere 3.6.23,when I go to u user, and try to change the timeline from "tweets and answer" to something else, Twidere crash with the following stack trace :

build.board: MSM8974
build.bootloader: unknown
build.brand: oneplus
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: A0001
build.display: MHC19Q
build.fingerprint: oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS3P0:user/release-keys
build.hardware: bacon
build.host: cyanogen
build.id: MHC19Q
build.manufacturer: OnePlus
build.model: A0001
build.product: bacon
build.radio: unknown
build.serial: eded4f49
build.tags: release-keys
build.time: 1470960791000
build.type: user
build.user: jenkins-internal
version.codename: REL
version.incremental: 2b5f277d1c
version.release: 6.0.1
version.sdk_int: 23

08-06 08:46:07.351 E/AndroidRuntime(24244): FATAL EXCEPTION: main
08-06 08:46:07.351 E/AndroidRuntime(24244): Process: org.mariotaku.twidere, PID: 24244
08-06 08:46:07.351 E/AndroidRuntime(24244): Theme: themes:{default=overlay:com.blazze11.euphoria.dark, iconPack:com.cyngn.hexo, fontPkg:com.blazze11.euphoria.dark, com.android.systemui=overlay:com.blazze11.euphoria.dark, com.android.systemui.navbar=overlay:com.blazze11.euphoria.dark}
08-06 08:46:07.351 E/AndroidRuntime(24244): java.lang.IllegalStateException: Fragment UserTimelineFilterDialogFragment{e427d43 #1 set_timeline_filter} declared target fragment UserTimelineFragment{df68446 #0 id=0x7f120154} that does not belong to this FragmentManager!
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1352)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.os.Handler.handleCallback(Handler.java:739)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.os.Looper.loop(Looper.java:148)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at java.lang.reflect.Method.invoke(Native Method)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-06 08:46:07.351 E/AndroidRuntime(24244): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Check before submitting issue -- Thank you!

You can ignore this form if this issue is a feature request.

## Steps to reproduce

Go to someone tweets and click on the "tweet and answerd" zone on top of the timeline

## Extra info

App version: (version code here)

Micro-blogging service:

- [ x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ x] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ x] Media preview enabled

**Comment by fanf** [comment]
It's corrected in 3.6.24, thanks!
